Repository wecode-bootcamp-korea/48-2nd-F_Kiiler-backend, pull requests merged in 2023-08, with the labels that each got.

#1 initial setting
  .env.sample
  .gitignore
  app.js
  package-lock.json
  package.json
  src/models/data-source.js
Labels: 멘토 리뷰 요청

#2 [ Database Schema after remove cached]
  .env.sample
  .gitignore
  db/migrations/20230823050009_create_agreements_table.sql
  db/migrations/20230823050048_create_users_table.sql
  db/migrations/20230823050116_create_categories_table.sql
  db/migrations/20230823050142_create_brands_table.sql
  db/migrations/20230823050204_create_products_table.sql
  db/migrations/20230823050238_create_sizes_table.sql
  db/migrations/20230823050307_create_bid_product_size_table.sql
  db/migrations/20230823050334_create_addresses_table.sql
  db/migrations/20230823050401_create_profile_images_table.sql
  db/migrations/20230823050429_create_bid_sells_table.sql
  db/migrations/20230823050447_create_bid_buys_table.sql
  db/migrations/20230823050505_create_orders_table.sql
Labels: 멘토 리뷰 요청, 수정 요청

#3 회원가입 기능 구현
  app.js
  src/controllers/user.controller.js
  src/models/user.dao.js
  src/routes/index.js
  src/routes/user.router.js
  src/services/user.service.js
  src/utils/error.js
Labels: 멘토 리뷰 요청

#4 로그인 기능 구현
  src/controllers/user.controller.js
  src/models/data.source.js
  src/routes/user.router.js
  src/services/user.service.js
  src/utils/auth.js
Labels: 멘토 리뷰 요청

#6 modify route
  app.js
  src/models/user.dao.js
Labels: Conflict 해결 요청, 완료

#7 로그인 기능 수정
  src/controllers/user.controller.js
  src/utils/auth.js
Labels: 멘토 리뷰 요청

#8 modify product_images table
  db/migrations/20230825124120_update_product_images_table.sql
Labels: 수정 요청

#9 구매/판매 각 사이즈별 가격 나타내기
  app.js
  src/controllers/buy.controller.js
  src/controllers/sell.controller.js
  src/controllers/user.controller.js
  src/models/buy.dao.js
  src/models/sell.dao.js
  src/routes/buy.router.js
  src/routes/index.js
  src/routes/sell.router.js
  src/services/user.service.js
  src/utils/auth.js
Labels: 멘토 리뷰 요청, 수정 요청

#15 진짜 최종
  src/models/buy.dao.js
  src/models/sell.dao.js
Labels: 멘토 리뷰 요청

#14 회원가입 수정
  src/controllers/product.controller.js
  src/controllers/user.controller.js
  src/models/data.source.js
  src/models/product.dao.js
  src/models/user.dao.js
  src/routes/index.js
  src/routes/product.router.js
  src/services/product.service.js
  src/services/user.service.js
Labels: Conflict 해결 요청, 완료

#13 상품 상세페이지 구현(브랜드, 상품명, 이미지)
  src/controllers/product.controller.js
  src/models/product.dao.js
  src/models/user.dao.js
  src/routes/index.js
  src/routes/product.router.js
  src/services/product.service.js
Labels: 수정 요청

#16 [전체리스트 filtering,sorting,page 구현]
  .gitignore
  src/controllers/list.controller.js
  src/controllers/sell.controller.js
  src/controllers/user.controller.js
  src/models/buy.dao.js
  src/models/list.dao.js
  src/models/sell.dao.js
  src/models/user.dao.js
  src/routes/index.js
  src/routes/list.router.js
  src/services/list.service.js
  src/services/user.service.js
Labels: 수정 요청

#11 [ 입찰 거래 시스템 api 구현 ]
  package-lock.json
  package.json
  src/controllers/bid.sell.controller.js
  src/models/bid.sell.dao.js
  src/models/enums.js
  src/routes/bid.router.js
  src/routes/index.js
  src/routes/user.router.js
  src/services/bid.sell.service.js
  src/services/user.service.js
Labels: Conflict 해결 요청, 멘토 리뷰 요청

#18 상세페이지 : 사이즈별 최근거래가, 판매/구매입찰가 나타내기
  src/controllers/product.controller.js
  src/models/product.dao.js
  src/models/user.dao.js
  src/routes/product.router.js
  src/services/product.service.js
Labels: 멘토 리뷰 요청

#20 sub query 이용하였을때 조건절 위치 변경
  src/models/list.dao.js
  src/services/list.service.js
Labels: 멘토 리뷰 요청
